# Generated by Django 4.2 on 2023-05-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='type',
            new_name='game_type',
        ),
    ]
